apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: airflow-kubes-pod
  name: airflow-kubes-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-kubes-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: airflow-kubes-pod
    spec:
      dnsPolicy: Default
      serviceAccountName: default
      containers:
      - image: airflow-kubes
        name: airflow-app
        resources: {}
        imagePullPolicy: Never